# Generated by Django 3.1.4 on 2020-12-27 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vlan',
            fields=[
                ('number', models.SmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True, max_length=150)),
                ('network', models.CharField(blank=True, max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='IPaddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.GenericIPAddressField(protocol='IPv4', unique=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('used', models.BooleanField(default=False)),
                ('vlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vlans.vlan')),
            ],
            options={
                'verbose_name': 'IPaddress',
                'verbose_name_plural': 'IPaddresses',
                'ordering': ['id'],
            },
        ),
    ]
